version: '3.0'

services:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_user
      MYSQL_USER: danxjj
      MYSQL_PASSWORD: Cabuto12
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    expose: 
      - "3307"

  userapi:
    image: ecommerceuserapi
    ports:
      - "81:80"
    build: 
      context: Backend/User
    depends_on:
      - database

  productapi:
    image: ecommerceproductapi
    ports:
      - "82:80"
    build:
      context: Backend/Product
    depends_on:
      - database

  paymentapi:
    image: ecommercepaymentapi
    ports:
      - "83:80"
    build:
      context: Backend/Payment
    depends_on:
      - database

  frontend:
    build: Frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Frontend/nginx-configs:/etc/nginx/conf.d
    environment:
      TZ: "America/Sao_Paulo"
    restart: unless-stopped

volumes:
  dbdata: