version: '3.0'

services:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: danxjj
      MYSQL_PASSWORD: Cabuto12
    command: --max_allowed_packet=32505856
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"

  userapi:
    container_name: userapi
    image: ecommerceuserapi
    # ports:
    #   - "81:80"
    build:
      context: Backend/User
    depends_on:
      - database

  productapi:
    container_name: productapi
    image: ecommerceproductapi
    # ports:
    #   - "82:80"
    build:
      context: Backend/Product
    depends_on:
      - database

  paymentapi:
    container_name: paymentapi
    image: ecommercepaymentapi
    # ports:
    #   - "83:80"
    build:
      context: Backend/Payment
    depends_on:
      - database

  apigateway:
    container_name: apigateway
    image: ecommerceapigateway
    ports:
      - "84:80"
    build:
      context: Backend/Gateway
    depends_on:
      - database

  frontend:
    build: Frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Frontend/nginx-configs:/etc/nginx/conf.d
    environment:
      TZ: "America/Sao_Paulo"
    restart: unless-stopped

volumes:
  dbdata:
